.Dd September 27, 2023
.Dt I2CA 1
.Sh NAME
.Nm i2ca
.Nd image to c array converter
.Sh SYNOPSIS
.Nm
.Op Fl fhv
.Op Fl n Ar variable_name
.Op Ar image_path
.Sh DESCRIPTION
The
.Nm
utility lets you convert an image to a c array.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl f
force conversion
.It Fl h
show usage
.It Fl v
display the program version
.It Fl n
specify the variable name
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/i2ca/issues
