.Dd November 23, 2022
.Dt PNG2CARR 1
.Sh NAME
.Nm png2carr
.Nd png to c array converter
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Fl i Ar input
.Op Fl n Ar variable_name
.Sh DESCRIPTION
The
.Nm
utility lets you convert a png image to a c array.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.It Fl i
specify the input file path
.It Fl n
specify the variable name
.El
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/png2carr/issues
